---
- name: install ceph-common
  apt: 
    name: ceph-common
    state: present

- name: reset ssh connection
  meta: reset_connection

- name: template add host to cluster
  template:
    src: ceph_orch_host_add.sh.j2
    dest: /tmp/ceph_orch_host_add.sh

#- name: add host to cluster
#  shell: "{{ lookup('template', 'ceph_orch_host_add.sh.j2') }}"

- name: add host to cluster
  shell: /bin/bash /tmp/ceph_orch_host_add.sh