---
# tasks file for ansible_openstack_ceph
- include_tasks: common.yml

- include_tasks: docker.yml

- name: reset ssh connection
  meta: reset_connection

- include_tasks: sshd.yml

- include_tasks: netplan.yml

- include_tasks: cephadm.yml
  when: inventory_hostname in groups['deployer']

- include_tasks: ceph.yml
  when: inventory_hostname in groups['deployer']

- include_tasks: ceph_mon.yml
  when: inventory_hostname in groups['deployer']

- include_tasks: ceph_osd.yml
  when: inventory_hostname in groups['deployer']

- include_tasks: ceph_pool_keyring.yml
  when: inventory_hostname in groups['deployer']

